In [38]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from word2number import w2n

In [43]:
data = pd.read_csv("salary 1.csv")
data

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [63]:
data.experience = data.experience.fillna("zero")
data

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         7.0                7   72000
7          11         7.0                8   80000

In [45]:
data.experience = data.experience.apply(w2n.word_to_num)
data

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [49]:
import math
median_test_score = math.floor(data['test_score'].mean())
median_test_score

7

In [51]:
data.test_score = data.test_score.fillna(median_test_score)
data

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         7.0                7   72000
7          11         7.0                8   80000

In [52]:
median_experience = math.floor(data['experience'].mean())
median_experience

4

In [56]:
data.experience = data.experience.fillna(median_experience)
data

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         7.0                7   72000
7          11         7.0                8   80000

In [59]:
reg  = linear_model.LinearRegression()
reg.fit(data[['experience','test_score','interview_score']],data.salary)

LinearRegression()

In [60]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [61]:
reg.intercept_

14992.65144669314

In [62]:
reg.predict([[2,9,6]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [65]:
2922.26901502*2+2221.30909959*9+2147.48256637*6+14992.65144669314

53713.86677126314

In [64]:
reg.predict([[12,10,10]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

In [66]:
2922.26901502*12+2221.30909959*10+2147.48256637*10+14992.65144669314


93747.79628653315